"""Filesystem paths shared by stacks that build assets."""

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

# Docker build context for every image in this project: both api/ and
# functions/* need shared/, so the context has to be backend/ rather than the
# individual function directory.
BACKEND_DIR = REPO_ROOT / "backend"

# Royalty-free background music, synced to the audio bucket under assets/.
ASSETS_DIR = REPO_ROOT / "assets"

# Lambda layers. Generated by scripts/build_layers.sh and gitignored;
# pipeline_stack warns at synth time when the shared layer is missing rather
# than failing, so `cdk synth` still works from a clean checkout.
SHARED_LAYER_DIR = REPO_ROOT / "layers" / "shared"

# Unused while the browser does the mixing. Kept so re-enabling the server-side
# mix_audio step is a wiring change in pipeline_stack, not a path hunt;
# `scripts/build_layers.sh ffmpeg` still populates it on demand.
FFMPEG_LAYER_DIR = REPO_ROOT / "layers" / "ffmpeg"
